name: Trigger auto deployment for container-app-kpxrq4mmllk74

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-kpxrq4mmllk74-AutoDeployTrigger-f13df512-3a70-46c2-be56-0dc12706c182.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKPXRQ4MMLLK74_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKPXRQ4MMLLK74_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKPXRQ4MMLLK74_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPKPXRQ4MMLLK74_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKPXRQ4MMLLK74_REGISTRY_PASSWORD }}
          containerAppName: container-app-kpxrq4mmllk74
          resourceGroup: appspacesragappaed9bbf6
          imageToBuild: default/container-app-kpxrq4mmllk74:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


